"""
tts.py — PocketTTS Streaming Core
===================================
Low-level PocketTTS wrapper used by synthesizer.py.

Only PocketTTSStreaming is kept here.  All token-buffering, sentence-splitting,
and HTTP serving logic lives in synthesizer.py and main.py respectively.

Piper and Coqui backends are handled entirely in synthesizer.py.
"""

import threading
import time
import numpy as np
import sounddevice as sd


# ============================================================================
# POCKET-TTS STREAMING TTS (Sub-50ms latency)
# ============================================================================

class PocketTTSStreaming:
    """
    PocketTTS direct-playback wrapper.

    Streams audio chunks to sounddevice as they are generated by the model —
    first audio heard in <50ms.  Used by the TTS microservice for local
    speaker output (the /speak endpoints).

    For HTTP synthesis (returning WAV bytes), use synthesizer.py directly.
    """

    def __init__(self, voice: str = "alba", rate: float = 1.0):
        """
        Args:
            voice: Voice name (alba, etc.)
            rate:  Speech rate multiplier (1.0 = normal)
        """
        try:
            from pocket_tts import TTSModel
            self.TTSModel = TTSModel
        except ImportError:
            raise ImportError(
                "pocket_tts not installed. Install with: pip install pocket-tts"
            )

        self.model       = self.TTSModel.load_model()
        self.voice_state = self.model.get_state_for_audio_prompt(voice)
        self.rate        = rate
        self.sample_rate = self.model.sample_rate

        self._is_speaking = False
        self._should_stop = False
        self._lock        = threading.Lock()

        # Persistent output stream — opened once, reused across chunks
        self._stream: sd.OutputStream | None = None

    # -------------------------------------------------------------------------

    def _ensure_stream(self):
        """Open the sounddevice stream if not already open."""
        if self._stream is None or not self._stream.active:
            self._stream = sd.OutputStream(
                samplerate=self.sample_rate,
                channels=1,
                dtype="float32",
                blocksize=512,   # 512 samples ≈ 23ms @ 22050Hz — low output latency
            )
            self._stream.start()

    def speak(self, text: str):
        """
        Synthesize and play text immediately.

        Audio chunks stream to the speaker as the model generates them —
        first audio in <50ms.  Blocks until synthesis is complete (not until
        playback finishes — the stream drains asynchronously).
        """
        if not text.strip():
            return

        with self._lock:
            self._is_speaking = True
            self._should_stop = False

        try:
            self._ensure_stream()

            for chunk in self.model.generate_audio_stream(self.voice_state, text):
                if self._should_stop:
                    break

                audio = chunk.numpy()

                # Rate adjustment (simple linear resampling)
                if self.rate != 1.0:
                    idx   = np.arange(0, len(audio), self.rate)
                    idx   = idx[idx < len(audio)].astype(int)
                    audio = audio[idx]

                if self._stream and self._stream.active:
                    self._stream.write(audio)

        except Exception as exc:
            import logging
            logging.getLogger("tts").error("PocketTTS speak error: %s", exc)
        finally:
            with self._lock:
                self._is_speaking = False

    def stop(self):
        """Interrupt playback immediately."""
        with self._lock:
            self._should_stop = True
            self._is_speaking = False

        try:
            sd.stop()
        except Exception:
            pass

        # Reset flag after brief delay so next speak() works
        def _reset():
            time.sleep(0.05)
            with self._lock:
                self._should_stop = False

        threading.Thread(target=_reset, daemon=True).start()

    @property
    def is_speaking(self) -> bool:
        with self._lock:
            return self._is_speaking

    def shutdown(self):
        """Clean shutdown — stop playback and close stream."""
        self.stop()
        if self._stream:
            try:
                self._stream.stop()
                self._stream.close()
            except Exception:
                pass
            self._stream = None
